# Utiliser une image de base complète
FROM python:3.12-bullseye

# Définir le répertoire de travail
WORKDIR /app/backend

# Installer les dépendances système
RUN apt-get update && apt-get install -y python3-distutils

# Copier les fichiers nécessaires
COPY backend/requirements.txt /app/backend/requirements.txt

# Installer les dépendances Python
RUN pip install -r requirements.txt

# Copier le reste des fichiers
COPY backend/ /app/backend/

# Expose le port sur lequel FastAPI écoutera
EXPOSE 8000

# Commande pour démarrer l'application FastAPI avec Uvicorn
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000" ,"--reload"]



