FROM python:3.12-slim

# Définit le répertoire de travail
WORKDIR /app

# Copie le fichier des dépendances
COPY requirements.txt app/requirements.txt

# Installe les dépendances
RUN pip install -r requirements.txt

# Copie le reste des fichiers dans le conteneur
COPY . /app

# Expose le port sur lequel FastAPI écoutera
EXPOSE 8000

# Commande pour démarrer l'application FastAPI avec Uvicorn
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000" ,"--reload"]



