name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Changez la branche si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise un runner GitHub Actions basé sur Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Récupère votre code source

      - name: Deploy to EC2
        uses: appleboy/scp-action@master  # Utilise l'action pour copier des fichiers via SCP
        with:
          host: ec2-50-17-32-22.compute-1.amazonaws.com  # Remplacez par l'adresse de votre instance EC2
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # La clé privée SSH, à ajouter comme secret dans votre dépôt GitHub
          source: "."  # Tous les fichiers du projet
          target: "/home/ubuntu/projet7"  # Répertoire cible sur l'EC2

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master  # Utilise l'action pour exécuter des commandes SSH
        with:
          host: ec2-50-17-32-22.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/projet8  # Naviguer vers le répertoire contenant docker-compose.yml
            git pull origin main  # Mettre à jour avec la dernière version du dépôt



