name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-18-234-236-155.compute-1.amazonaws.com  # Adresse IP publique correcte
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/projet8"

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-234-236-155.compute-1.amazonaws.com  # Adresse IP publique correcte
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo fuser -k 8000/tcp
            sudo fuser -k 8501/tcp
            sudo apt update
            sudo apt upgrade -y  # Met à jour tous les paquets
            sudo apt install -y python3-setuptools

            # Arrêter les conteneurs Docker sans les supprimer
            docker stop $(docker ps -q)

            cd /home/ubuntu/projet8
            git pull origin main
            source myenv/bin/activate
            cd api
            nohup uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload &
            nohup streamlit run streamlit_app.py --server.port 8501 &





